
update stretchy_report sr

set sr.report_sql = 'select msa.account_no as \'Group Account\',\nmg.display_name as \'Group Name\',\nmi.invested_amount as \'Invested Amount\',\nctie.investment_start_date as \'Investment Start Date\',\nctie.investment_close_date as \'Investment Close Date\',\ncts.earning_status as \'Status\',\nconcat(ml.account_no, \'-\' , ml.external_id) as \'Loan Account\',\nmpl.name as \'Product Name\',\nml.approved_principal as \'Investment Amount\',\nmlc.amount as \'Charge Amount\',\nml.maturedon_date as \'Maturity Date\'\n\n\nfrom  m_office mo \njoin m_office office on office.hierarchy like concat(mo.hierarchy, \'%\') \nand office.hierarchy like concat(\'${currentUserHierarchy}\',\'%\')\n \nleft join ct_posted_investment_earnings ctie on office.id = ctie.office_id\n\nleft join  m_investment mi on ctie.loan_id = mi.loan_id and mi.saving_id = ctie.saving_id\nleft join m_loan ml on mi.loan_id = ml.id\nleft join m_product_loan mpl on mpl.id = ml.product_id\nleft join m_savings_account msa on msa.id = mi.saving_id\nleft join m_group mg on mg.id = msa.group_id\nleft join ct_investment_status cts on cts.loan_id = mi.loan_id\nleft join m_loan_charge mlc on ml.id = mlc.loan_id\n\n\nWHERE\n    CASE\n 	 WHEN \'${investmentAccountNo}\' != \'NULL\'  THEN\n  	 	ml.account_no = \'${investmentAccountNo}\'\n 	 ELSE\n   	  1=1 \n	END\n	\n	AND\n	\n	CASE \n	 WHEN \'${investedStartDate}\' != \'NULL\' THEN\n         CASE WHEN \'${investedEndDate}\' != \'NULL\' THEN\n        		 ctie.investment_start_date  BETWEEN \'${investedStartDate}\' AND \'${investedEndDate}\'\n		    ELSE\n           ctie.investment_start_date  BETWEEN \'${investedStartDate}\' AND curDate()\n         END\n		 \n     ELSE 1=1\n   \n   END\n   \n   AND \n   \n   CASE WHEN \'${loanProductId}\' != \'NULL\' THEN\n	    mpl.id = \'${loanProductId}\'\n		ELSE 1=1\n   END  \n	  \n   AND\n	\n   CASE \n    WHEN \'${ml.maturedon_date}\' != \'NULL\'  THEN\n        CASE WHEN \'${maturityEndDate}\' != \'NULL\' THEN\n    	   ml.maturedon_date BETWEEN \'${maturityStartDate}\' AND \'${maturityEndDate}\'\n        ELSE\n          ml.maturedon_date BETWEEN \'${maturityStartDate}\' AND curDate()\n		  END	 	  \n     ELSE 1=1    \n  END\n\ngroup by  mi.loan_id,  mi.saving_id'

where sr.report_name = 'Investment Status Report' and sr.report_category = 'Investment Status Report';




update stretchy_report sr
set sr.report_sql = 'select mg.id as \'Group No\',\nmg.display_name as \'Group Name\',\nconcat(mpl.name, \' - \', ml.external_id) as \'Invested In\',\nctie.investment_start_date as \'Investment Start Date\',\nctie.investment_close_date as \'Investment Close Date\',\nmi.invested_amount as \'Invested Amount\',\nctie.interest_earned as \'Total Interest Earned\',\nctie.gorup_interest_earned as \'Groups Interest Earned\',\nctie.caritas_interest_earned as \'Caritas Interest Earned\', \nmlc.amount as \'Total Charge Amount\',\nctie.number_of_days as \'No.Of Days\',\ncts.earning_status as \'Status\',\nml.maturedon_date as \'Maturity Date\'\n\n\nfrom m_office mo \njoin m_office office on office.hierarchy like concat(mo.hierarchy, \'%\') \nand office.hierarchy like concat(\'${currentUserHierarchy}\',\'%\')\n \nleft join ct_posted_investment_earnings ctie on office.id = ctie.office_id\n\nleft join m_investment mi on ctie.loan_id = mi.loan_id and ctie.saving_id = mi.saving_id\nleft join m_loan ml on mi.loan_id = ml.id\nleft join m_product_loan mpl on mpl.id = ml.product_id\nleft join m_savings_account msa on msa.id = mi.saving_id\nleft join m_group mg on mg.id = msa.group_id\nleft join ct_investment_status cts on cts.loan_id = mi.loan_id\nleft join m_client mc on ml.client_id = mc.id\nleft join m_loan_charge mlc on ml.id = mlc.loan_id\n\nWHERE\n    CASE\n 	 WHEN \'${investmentAccountNo}\' != \'NULL\'  THEN\n  	 	ml.account_no = \'${investmentAccountNo}\'\n 	 ELSE\n   	  1=1 \n	END\n	\n	AND\n	\n	CASE \n	 WHEN \'${investedStartDate}\' != \'NULL\' THEN\n         CASE WHEN \'${investedEndDate}\' != \'NULL\' THEN\n        		 ctie.investment_start_date  BETWEEN \'${investedStartDate}\' AND \'${investedEndDate}\'\n		    ELSE\n          ctie.investment_start_date  BETWEEN \'${investedStartDate}\' AND curDate()\n         END\n		 \n     ELSE 1=1\n   \n   END\n   \n   AND \n   \n   CASE WHEN \'${loanProductId}\' != \'NULL\'  THEN\n	    mpl.id = \'${loanProductId}\'\n		ELSE 1=1\n   END  \n	  \n   AND\n	\n   CASE \n    WHEN \'${ml.maturedon_date}\' != \'NULL\'  THEN\n        CASE WHEN \'${maturityEndDate}\' !=\'NULL\' THEN\n    	   ml.maturedon_date BETWEEN \'${maturityStartDate}\' AND \'${maturityEndDate}\'\n        ELSE\n          ml.maturedon_date BETWEEN \'${maturityStartDate}\' AND curDate()\n		  END	 	  \n     ELSE 1=1    \n  END\ngroup by ml.id, msa.id'

where sr.report_name = 'Investment Distribution Report' 
and sr.report_category = 'Investment Distribution Report';